### ISSUE TITLE
node_modules folder alias

### ISSUE THREAD

**Issue by ali-master** [garousianstudio/starter-webpack-react-es6-sass#1]
https://github.com/garousianstudio/starter-webpack-react-es6-sass/blob/f6388afe95fc26b5f77e3baba86b1bc01e500e49/webpack.common.js#L53

Hi there,

When we are using the webpack, then we don't need to alias node_modules folder into the config file because webpack will be mapping installed node packages into the node_module folder by default.

**Comment by garousianstudio** [comment]
Hi Ali,
That's quite right, thanks for mentioning that! I merged your pull request.
